export const UPDATE_STORYBOARD = 'UPDATE_STORYBOARD'
export const RETRIEVE_STORYBOARD = 'RETRIEVE_STORYBOARD'
export const ADDING_STORYBOARD = 'ADDING_STORYBOARD'
export const DELETING_STORYBOARD = 'DELETING_STORYBOARD'